package com.adda;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@EnableSwagger2
public class AddaApplication {
	public static void main(String[] args) {
		SpringApplication.run(AddaApplication.class, args);
	}
}

// eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjUyODI3NTQ4LCJpYXQiOjE2NTI4MjcyNDgsImp0aSI6ImM5ZjljOGNjNzYwOTQxMGU5Nzk5YWI0NGMxMDFjMGNkIiwidXNlcl9pZCI6NCwiZmlyc3RfbmFtZSI6IkJvaGRhbiIsImxhc3RfbmFtZSI6IkthdHNldnljaCIsInVzZXJuYW1lIjoiYmthdHNldnljaCIsImVtYWlsIjoiYmthdHNldnljaEBpY2xvdWQuY29tIiwiaXNfc3VwZXJ1c2VyIjpmYWxzZX0.sVGwlHI4AOif-5Q9mEaUf0ry--TQVQm-Q6wC8FjUDcw