create sequence hibernate_sequence start 1 increment 1;
create table advertisements
(
    id                   uuid not null,
    date                 varchar(255),
    description          varchar(255),
    price                float4,
    qr_code              varchar(255),
    title                varchar(255),
    viewers              int4,
    category_category_id int8,
    photos_id            int8,
    user_id              int8,
    primary key (id)
);
create table categories
(
    category_id   int8 generated by default as identity,
    category_name varchar(255),
    primary key (category_id)
);
create table histories
(
    id int8 not null,
    primary key (id)
);
create table histories_adverts
(
    history_id int8 not null,
    adverts_id uuid not null
);
create table photos
(
    id     int8 generated by default as identity,
    photo1 varchar(255),
    photo2 varchar(255),
    photo3 varchar(255),
    photo4 varchar(255),
    photo5 varchar(255),
    photo6 varchar(255),
    photo7 varchar(255),
    photo8 varchar(255),
    size   int4,
    primary key (id)
);
create table refresh_token
(
    id          int8 generated by default as identity,
    expiry_date timestamp,
    token       varchar(255),
    user_id     int8,
    primary key (id)
);
create table roles
(
    id   int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table update_token
(
    token          varchar(255) not null,
    expiry_date    timestamp,
    sensitive_data varchar(255),
    user_id        int8,
    primary key (token)
);
create table url
(
    id              int8 not null,
    creation_date   timestamp,
    expiration_date timestamp,
    original_url    varchar(255),
    short_link      varchar(255),
    primary key (id)
);
create table user_roles
(
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id)
);
create table users
(
    id                int8 generated by default as identity,
    email             varchar(255),
    enabled           boolean not null,
    first_name        varchar(255),
    last_name         varchar(255),
    password          varchar(255),
    username          varchar(255),
    verification_code varchar(255),
    wish_list         uuid,
    primary key (id)
);
create table wishlist
(
    id      uuid not null,
    user_id int8,
    primary key (id)
);
create table wishlist_adverts
(
    wish_list_id uuid not null,
    adverts_id   uuid not null
);

alter table if exists histories_adverts add constraint UK_72rr913nob8msjpwydobasbj8 unique (adverts_id);
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists wishlist_adverts add constraint UK_rco5alhmd1xo46axpjyot9f46 unique (adverts_id);
alter table if exists advertisements add constraint FKkk60c90dq3rtnyemsiku7lsv7 foreign key (category_category_id) references categories;
alter table if exists advertisements add constraint FKl0bvnwn8jo9h2blta2nturfof foreign key (photos_id) references photos;
alter table if exists advertisements add constraint FKj69sc4qf7g4p52q8vl0hqvbmp foreign key (user_id) references users;
alter table if exists histories_adverts add constraint FKp323t78v1m672xhiean5e413s foreign key (adverts_id) references advertisements;
alter table if exists histories_adverts add constraint FKqo465vtlhrvd941wfwsgdcfup foreign key (history_id) references histories;
alter table if exists refresh_token add constraint FKjtx87i0jvq2svedphegvdwcuy foreign key (user_id) references users;
alter table if exists update_token add constraint FKjxe4uuphemvh8ksr8fje908yu foreign key (user_id) references users;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists wishlist_adverts add constraint FKack99ymvrh9dnnshflqm4958k foreign key (adverts_id) references advertisements;
alter table if exists wishlist_adverts add constraint FKet6u9a9gs90gc9vphnoykax59 foreign key (wish_list_id) references wishlist;